{{- if not contains "enterprise" .Values.imageTag}}
# This service is intended for clients running in kubernetes to connect to the
# cluster replica set.  This distinguishes it from discovery-lb which is about 
# cluster formation and internal communication.

apiVersion: v1
kind: Service
metadata:
  name: {{ template "neo4j.replica.fullname" . }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/name: {{ template "neo4j.replica.fullname" . }}
    app.kubernetes.io/component: core
spec:
  clusterIP: None
  publishNotReadyAddresses: true 
  ports:
    - name: http
      port: 7474
      targetPort: 7474
    - name: bolt
      port: 7687
      targetPort: 7687
    - name: https
      port: 7473
      targetPort: 7473
  selector:
    app.kubernetes.io/name: {{ template "neo4j.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/component: replica

{{- end }}